title: Use appropriate tabIndex values
rule: >-
  Ensure tabIndex values are either 0 or -1. Positive tabIndex values disrupt the natural tab order and can create accessibility issues.
severity: high
scope: file
examples:
  - snippet: "function MyDiv() {\n    return (\n        <div>\n            <span tabIndex=\"5\">foo</span> // Noncompliant\n            <span tabIndex=\"3\">bar</span> // Noncompliant\n            <span tabIndex=\"1\">baz</span> // Noncompliant\n            <span tabIndex=\"2\">qux</span> // Noncompliant\n        </div>\n    );\n}"
    isCorrect: false
  - snippet: "function MyDiv() {\n    return (\n        <div>\n            <span tabIndex=\"0\">foo</span>\n            <span tabIndex=\"-1\">bar</span>\n            <span tabIndex={0}>baz</span>\n            <span>qux</span>\n        </div>\n    );\n}"
    isCorrect: true
inheritance:
  inheritable: true
  exclude: []
  include: []
